default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: gozenapp_development

test:
  <<: *default
  database: gozenapp_test

production:
  <<: *default
  database: <%= Rails.application.credentials.database[:production][:db_name] %>
  username: <%= Rails.application.credentials.database[:production][:user] %>
  password: <%= Rails.application.credentials.database[:production][:password] %>
  host: <%= Rails.application.credentials.database[:production][:host] %>
  port: <%= Rails.application.credentials.database[:production][:port] %>
