Item.create(id: 1, menu: "curry_set", price: 150)
Item.create(id: 2, menu: "cake_set", price: 600)
Item.create(id: 3, menu: "curry", price: 1200)
Item.create(id: 4, menu: "salad", price: 300)
Item.create(id: 5, menu: "coffee", price: 300)
Item.create(id: 6, menu: "cake", price: 400)

Relationship.create(id: 1, set_menu_id: 1, food_id: 3)
Relationship.create(id: 2, set_menu_id: 1, food_id: 4)
Relationship.create(id: 3, set_menu_id: 1, food_id: 5)
Relationship.create(id: 4, set_menu_id: 2, food_id: 5)
Relationship.create(id: 5, set_menu_id: 2, food_id: 6)